version: '3.8'
services:
  webapi:
    build:
      context: .
      dockerfile: ./Dockerfiles/webapi.dockerfile
    ports:
      - "5000:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=chat_db;User Id=sa;Password=Trk4889!;TrustServerCertificate=True;"
    volumes:
      - ./WebAPI/:/app
      - /app/bin
      - /app/obj
    stdin_open: true
    tty: true
    depends_on:
      - sqlserver
  sqlserver:
    build:
      context: ./Dockerfiles
      dockerfile: sqlserver.dockerfile
    environment:
      SA_PASSWORD: "Trk4889!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    restart: always
    volumes:
      - sql_data:/var/opt/mssql
  dotnet:
    image: mcr.microsoft.com/dotnet/sdk:9.0
    working_dir: /dotnet
    entrypoint: ["/bin/bash"]
    volumes:
      - ./WebAPI:/dotnet
    stdin_open: true
    tty: true
volumes:
  sql_data: